*** Variables ***
${HEADER_ACCESS}       BRASIL
${ACCESS_SMART_FIT}    xpath=//android.widget.Button[@content-desc="ACESSO SMART FIT"]
${HEADER_LOGIN}        Login   
${FILL_IN_CPF}         xpath=//android.widget.EditText  
${CLICK_SIGN_IN}       xpath=//android.widget.Button[@content-desc="ENTRAR"]
${HEADER_PIN}          Digite o código
${FILL_IN_PIN}         xpath=//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.EditText/android.widget.EditText
${HEADER_FEED}         App